defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "straight-cifar10" # change here for cifar100
method: "straight"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  straight_loss_weight: 7.5
  sim_loss_weight: 0.0
  var_loss_weight: 15.0
  cov_loss_weight: 1.0
  sequence: True
  multi_layer: True
  layers: [1]
data:
  dataset: cifar10 # change here for cifar100
  train_path: "./datasets"
  val_path: "datasets/imagenet100/val"
  format: "image_folder"
  num_workers: 4
# augmentations:
#   - straight: False
#     rrc:
#       enabled: True
#       crop_min_scale: 0.2
#       crop_max_scale: 1.0
#     color_jitter:
#       enabled: True
#       brightness: 0.4
#       contrast: 0.4
#       saturation: 0.2
#       hue: 0.1
#       prob: 0.8
#     grayscale:
#       enabled: True
#       prob: 0.2
#     gaussian_blur:
#       enabled: False
#       prob: 0.0
#     solarization:
#       enabled: True
#       prob: 0.1
#     equalization:
#       enabled: False
#       prob: 0.0
#     horizontal_flip:
#       enabled: True
#       prob: 0.5
#     crop_size: 32
#     num_crops: 2
augmentations:
  - straight: True
    straight_transform:
      enabled: True
      translation:
        scale_low: 0.2
        scale_high: 0.6
        intensity: 0.1
      tofro:
        scale_low: 0.2
        scale_high: 0.4
        intensity: 0.1
      rotation:
        scale_low: 0.2
        scale_high: 1.0
        intensity: 0.1
      t: 2 # number of time points = t + 1
      prob: [0.5, 0.5]
    color_jitter:
      enabled: True
      brightness: 0.4
      contrast: 0.4
      saturation: 0.2
      hue: 0.1
      prob: 0.8
    grayscale:
      enabled: True
      prob: 0.2
    gaussian_blur:
      enabled: False
      prob: 0.0
    solarization:
      enabled: True
      prob: 0.1
    equalization:
      enabled: False
      prob: 0.0
    horizontal_flip:
      enabled: True
      prob: 0.5
    crop_size: 32
    num_crops: 3 # should be straight_transform.t + 1
optimizer:
  name: "lars"
  batch_size: 64 # batch_size per device
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
# optimizer:
#   name: "adam"
#   batch_size: 64 # batch_size per device
#   lr: 0.001
#   classifier_lr: 0.001
#   weight_decay: 1e-6
# optimizer:
#   name: "adamw"
#   batch_size: 64 # batch_size per device
#   lr: 0.001
#   classifier_lr: 0.001
#   weight_decay: 0.01 # default value in pytorch
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "/mnt/ceph/users/xniu1/solo-learn-new/trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1000
devices: [0, 1, 2, 3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
# precision: 16-mixed
precision: 32
